# Generated by Django 3.2.4 on 2021-10-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='opportunities.Skills'),
        ),
    ]
