# Generated by Django 3.2.4 on 2021-11-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='companyname',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='job',
            name='application_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Rejected', 'Rejected'), ('Received Offer', 'Received Offer')], max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship')], max_length=255),
        ),
    ]
