# Generated by Django 3.2.4 on 2021-11-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_auto_20211115_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_status',
            field=models.CharField(choices=[('Not Yet Applied', 'Not Yet Applied'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Rejected', 'Rejected'), ('Received Offer', 'Received Offer')], max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='opportunities.Skills'),
        ),
    ]
