# Generated by Django 3.2.4 on 2021-11-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_alter_contacts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='opportunities.Skills'),
        ),
    ]
