# Generated by Django 3.2.4 on 2021-11-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='opportunities.Skills'),
        ),
    ]
