# Generated by Django 3.2.4 on 2021-11-17 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunities", "0010_alter_job_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="skills",
            name="user",
            field=models.ForeignKey(
                default=9, on_delete=django.db.models.deletion.CASCADE, to="auth.user"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(to="opportunities.Skills"),
        ),
    ]
